baseURL: https://michalbrylka.github.io/
languageCode: en-us
languageName: English
copyright: '&copy; Copyright 2019-2022 Michał Bryłka'
title: "Michał Bryłka | Devexcellence"

theme: LoveIt

enableEmoji: true

# googleAnalytics: G-TFL0Z5DXWF
#enableRobotsTXT: true

author:
  name: Michał Bryłka
  email: 'michal.brylka@gmail.com'
  link: 'https://github.com/MichalBrylka'  

outputs:
  home: ["HTML", "RSS", "JSON"]  
  
params: 
  defaultTheme: dark # site default theme ["auto", "light", "dark"]
  title: "Michał Bryłka | Devexcellence"
  dateFormat: "2006-01-02"

  header:
    title:
      logo: ''
      name: "Devexcellence"
      pre: '<i class="fa-solid fa-code" ></i>'


      post: ''
      typeit: false   
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: 'michal.brylka@gmail.com'
      avatarURL: /images/MichalBrylka.jpg
      title: 'Michał Bryłka | Devexcellence'
      subtitle: 'My fabulous adventures with coding for 20+ years'
      typeit: true
      social: true      
    posts:
      enable: true
      paginate: 10
  social:
    GitHub: 'MichalBrylka'
    Linkedin: 'michalbrylka'
    Twitter: 'michal_brylka'    
    Facebook: 'Michal.Brylka'
    # RSS: ""
  page:    
    hiddenFromSearch: false    
    fontawesome: true
    linkToMarkdown: false
    fraction: true
    math:
      enable: true     
      copyTex: true
      mhchem: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true
      Whatsapp: false
      Pinterest: false
      Tumblr: true
      HackerNews: true
      Reddit: true
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Flipboard: false
      Weibo: true
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: true
        shortname: 'michalbrylka' # Disqus shortname to use Disqus in posts
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1


menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
markup:
  highlight:
    noClasses: false
