baseURL: https://michalbrylka.github.io/
languageCode: en-us
languageName: English
copyright: '&copy; Copyright 2019-2022 Michał Bryłka'
title: "Michał Bryłka | Devexcellence"

theme: LoveIt

enableEmoji: true

# disqusShortname: nemesissoft

# googleAnalytics: G-TFL0Z5DXWF

author:
  name: Michał Bryłka
  email: 'michal.brylka@gmail.com'
  link: 'https://github.com/MichalBrylka'  

outputs:
  home: ["HTML", "RSS", "JSON"]   

params: 
  header:
    title:
      logo: ''
      name: "Devexcellence"
      pre: '<i class="fa-solid fa-code" ></i>'


      post: ''
      typeit: false   
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: 'michal.brylka@gmail.com'
      avatarURL: /images/MichalBrylka.jpg
      title: 'Michał Bryłka | Devexcellence'
      subtitle: 'My fabulous adventures with coding for 20+ years'
      typeit: true
      social: true      
    posts:
      enable: true
      paginate: 10
  social:
    GitHub: 'MichalBrylka'
    Linkedin: 'michalbrylka'
    Twitter: 'michal_brylka'    
    Facebook: 'Michal.Brylka'
  page:    
    hiddenFromSearch: false    
    fontawesome: true
    linkToMarkdown: true
    fraction: true
    math:
      enable: true     
      copyTex: true
      mhchem: true

  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1


menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
markup:
  highlight:
    noClasses: false
